name: Rebase

on:
  push:
    branches: [main]

jobs:
  rebase:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: peter-evans/rebase@6720916065562e44df6007404d22129ce5583978
        with:
          base: main
          include-labels: "Rebase automatically"
